### ISSUE TITLE
First error log message are aggregating a lot of repositories

### ISSUE THREAD

**Issue by robsonpeixoto** [caarlos0/clone-org#17]

**Comment by robsonpeixoto** [comment]
Sorry, but I can sent to you the repository names. But try to run the command twice and you will see that the first log line will "aggregate" a lot of repositories on the same log message.

**Comment by caarlos0** [comment]
hmm here it works fine

<img width="651" alt="image" src="https://user-images.githubusercontent.com/245435/91660094-74044c00-eaaa-11ea-9f57-87e28d8a6d57.png">

**Comment by robsonpeixoto** [comment]
I gota the problem. Is the limit of open files. The command os [not limiting](https://github.com/caarlos0/clone-org/blob/master/cmd/clone-org/main.go#L63-L76) the number of currents processes and is reach the limit of file descriptors.

I'm closing this issue because it is a config problem. But a suggestion is putting a limiting of currents jobs.

```
❯ ulimit -a
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8192
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2784
-n: file descriptors                256
```
