### ISSUE TITLE
Add Bitbucket support?

### ISSUE THREAD

**Issue by murielsilveira** [caarlos0/clone-org#5]
Do you think about adding support for bitbucket (or others) or would you rather have a new project for those? :)

**Comment by caarlos0** [comment]
I think it could be added... willing to open a PR ? :D

**Comment by murielsilveira** [comment]
Now I'm on into create a PR 💃 

Any idea on the cli interface?

**Comment by caarlos0** [comment]
maybe just `--provider=bitbucket` or something like that?

than we can just make `--provider=github` the default...

I assume that bitbucket will also have a token, so we can just update the help and etc about the `--token` flag (and the `GITHUB_TOKEN` env).

what do you think?
